title: Emaleth's Playground
author:	Emaleth
description: Bad code by nature

# generate social links in footer
twitter_username: EmalethDev
github_username:  Emaleth-BSE
youtube_username: channel/UCMWrvCUwZyBYuLbhGB6P-Cg

show_excerpts: true

minima:
  date_format: "%d-%m-%Y"
#  skin: dark

header_pages:
 - index.md
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
