title: Emaleth's Playground
author:	Emaleth
description: // bad code by design //

twitter_username: EmalethDev
github_username:  Emaleth-BSE

show_excerpts: true

minima:
  date_format: "%d-%m-%Y"
  google_analytics: G-ZGB569H81C

header_pages:
 - index.md
 - blog.md
 - about.md
 - contact.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag