title: "Emaleth's Playground"
author:
  name: "Emaleth"
  
description: "// bad code by design //"
show_excerpts: true
excerpt_separator: "<!--more-->"
remote_theme: "jekyll/minima"
minima:
  skin: "dark"
  date_format: "%H:%M %d-%m-%Y"
  social_links:
    twitter: "EmalethDev"
    github: "Emaleth"
    youtube: "Emaleth"
    youtube_channel: "UCMWrvCUwZyBYuLbhGB6P-Cg"
    youtube_channel_name: "Emaleth's Playground"

include:
 - _pages

exclude:
 - README.md

header_pages:
 - home.md
 - about.md
 - donations.md
 - contact.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme