title: Emaleth's Playground

author:
  name:	Emaleth

description: // bad code by design //

show_excerpts: true

remote_theme: jekyll/minima

minima:
  date_format: "%d-%m-%Y"
  social_links:
    twitter: EmalethDev
    github:  Emaleth
    youtube_channel: UCMWrvCUwZyBYuLbhGB6P-Cg
    youtube_channel_name: Emaleth
  skin: dark

include:
 - _pages
 
header_pages:
 - _pages/master_plan.md
 - _pages/home.md
 - _pages/blog.md
 - _pages/repositories.md
 - _pages/about.md
 - _pages/contact.md

excerpt_separator: "<!--more-->"

google_analytics: G-ZGB569H81C

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme
