title: "Emaleth's Playground"
author:
  name: "Emaleth"
  
description: "// bad code by design //"
show_excerpts: true
excerpt_separator: "<!--more-->"
remote_theme: "jekyll/minima"
minima:
  skin: "dark"
  date_format: "%H:%M %d-%m-%Y"

include:
 - _pages
 - _games

exclude:
 - README.md

header_pages:
 - _pages/home.md
 - _pages/blog.md
 - _pages/games.md
 - _pages/donations.md
 - _pages/about.md
 - _pages/contact.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme