title: Emaleth's Playground

author:
  name:	Emaleth

description: // bad code by design //

show_excerpts: true

remote_theme: jekyll/minima

minima:
  date_format: "%d-%m-%Y"
  social_links:
    twitter: EmalethDev
    github:  Emaleth-BSE
    youtube_channel: UCMWrvCUwZyBYuLbhGB6P-Cg
    youtube_channel_name: Emaleth
  skin: dark

header_pages:
 - index.md
 - about.md
 - contact.md

google_analytics: G-ZGB569H81C

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme