# Welcome to Beautiful Jekyll!
remote_theme: "daattali/beautiful-jekyll"
title: "Emaleth's Playground"
author: "Emaleth"
navbar-links:
  Home: "/"
  Games: "games"
  Blog: "blog"
  Donations: "donations"
  About: "about"
  Contact: "contact"

avatar: "/assets/img/Logo.png"
round-avatar: true
social-network-links:
  github: "Emaleth"
  twitter: "EmalethDev"
  youtube: "channel/UCMWrvCUwZyBYuLbhGB6P-Cg"
  reddit: "EmalethDev"
  spotify: "j48c3mja372gszea3lklehgvq"

rss-description: This website is a virtual proof that I'm awesome
share-links-active:
  twitter: true
  facebook: false
  linkedin: false
  vk: false

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

keywords: "game, gamedev, godot, github, Emaleth, beleth, valefar, entertainment"

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

site-css:
  - "/assets/css/custom-styles.css"

# site-js:
#   - "/assets/js/custom-script.js"

date_format: "%H:%M %d-%m-%Y"
timezone: "Europe/Rome"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: true
      head-extra: favicon.html
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"
      head-extra: favicon.html
      head-extra: motd-strip.html
      
exclude:
  - CNAME
  - LICENSE
  - README.md

include:
  - _pages
  - _games

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap


