name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Push a file to another repository
      uses: Emaleth/Automaton@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.AUTOMATON_TOKEN }}
      with:
        target_repo: 'Emaleth/Emaleth.github.io'
        target_file_name: 'Site'
        permalink: /site/
        title: 'Emaleth.dev'

